// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGIc3E2a8hNgjUcPHeJvx4nvXfcTItZK0',
    appId: '1:763842734570:android:0b3be7753ec6b1ca186a93',
    messagingSenderId: '763842734570',
    projectId: 'lastcheck-8ab2b',
    storageBucket: 'lastcheck-8ab2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6sqVg2G3Bcl3j9Ii65p_Wwev7gK68_J4',
    appId: '1:763842734570:ios:86c05b5634e772f1186a93',
    messagingSenderId: '763842734570',
    projectId: 'lastcheck-8ab2b',
    storageBucket: 'lastcheck-8ab2b.appspot.com',
    iosBundleId: 'com.example.appuserlogin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkUtHnPlOhs_XSLII1s7zOAQ0ZJXnX01Q',
    appId: '1:763842734570:web:8d24633b283f703a186a93',
    messagingSenderId: '763842734570',
    projectId: 'lastcheck-8ab2b',
    authDomain: 'lastcheck-8ab2b.firebaseapp.com',
    storageBucket: 'lastcheck-8ab2b.appspot.com',
    measurementId: 'G-EL9CKPH9NV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6sqVg2G3Bcl3j9Ii65p_Wwev7gK68_J4',
    appId: '1:763842734570:ios:86c05b5634e772f1186a93',
    messagingSenderId: '763842734570',
    projectId: 'lastcheck-8ab2b',
    storageBucket: 'lastcheck-8ab2b.appspot.com',
    iosBundleId: 'com.example.appuserlogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkUtHnPlOhs_XSLII1s7zOAQ0ZJXnX01Q',
    appId: '1:763842734570:web:d4347621c0fbb25f186a93',
    messagingSenderId: '763842734570',
    projectId: 'lastcheck-8ab2b',
    authDomain: 'lastcheck-8ab2b.firebaseapp.com',
    storageBucket: 'lastcheck-8ab2b.appspot.com',
    measurementId: 'G-NGQJWDRC3R',
  );

}